### ISSUE TITLE
Mirror issues on iOS 11.3

### ISSUE THREAD

**Issue by rsodre** [quellish/AirPlayStoryboards#1]
Hi.

My app based on this sample is having mirror issues after the iOS 11.3 upgrade. Used to work lke a charm, now the video is not being sent to AppleTV. I see the video on the device and the second display on AppleTV.

Any clues?
Did Apple change anything about airPlay on iOS 11.3?

**Comment by rsodre** [comment]
I forgot how much I altered the project. In my app, I open an AVPlayerViewController which video would replace the second display automatically. But in iOS 11.3 i had to specifically say it should replace our second display on my AVPlayer:
```
avplayer.allowsExternalPlayback = YES;
avplayer.usesExternalPlaybackWhileExternalScreenIsActive = YES;

```

**Comment by quellish** [comment]
Two things.

First, this sample was intended to demonstrate using AirPlay for a secondary display rather than media playback. Media playback is a different use case and there are specific APIs for it. This is more for using an AppleTV or external display for other content (for example: images, UI, games where an iPhone is a controller and AppleTV is the display). Apple does have a lot of documentation and examples for media playback, and with AVPlayerViewController they make it very easy.

Second, iOS 11.3 introduced AirPlay 2. So yes, there is something different! Under the hood the AirPlay implementation is completely different. Apple has updated documentation that would very much apply to your use case:

https://developer.apple.com/documentation/avfoundation/airplay_2/getting_airplay_2_into_your_app?language=objc
